### PR TITLE
Fix failure rendering styles that use glyphs or sprites

### LINKED ISSUE #5: Glyphs fail to load

### PR DESCRIPTION
**Pull request by JesseCrocker**
* Fixes error loading glyphs and sprites, fixes #5 
* update to mapbox-gl 5.0
* Adds additional logging for resource loading failures.

### CODE REVIEW

File: mapUtils.js [hunk 1]
```diff
@@ -60,6 +60,8 @@ exports.calculateZoom = function(extent, width, height) {
 
 exports.addOverlayDataToStyle = function(style, overlay) {
   return {
+    glyphs: style["glyphs"] || "",
```
Comment (JesseCrocker) [inline mapUtils.js]: This is the actual fix. We were failing to include the glyph url in the merged style, so of course loading glyphs failed.

File: getMap.js [hunk 2]
```diff
@@ -29,7 +30,7 @@ function getMap() {
           callback(null, response);
           debug("Request for " + req.url + " complete in " + (Date.now() - start) + "ms");
         });
-      } else {
+      } else if (protocol == "http" || protocol == "https") {
```
Comment (jczaplew) [inline getMap.js]: It is best to use `===` for strict comparisons 
```suggestion
      } else if (protocol === "http" || protocol === "https") {
```
